apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-env
  template:
    metadata:
      labels:
        app: deploy-env
    spec:
      containers:
      - name: deploy-env-container
        image: boluwole/deploy-env:latest
        ports:
        - containerPort: 22
        - containerPort: 8080
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
