kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 8080
        protocol: TCP
      - containerPort: 30002
        hostPort: 22
        protocol: TCP
    labels:
      instance-group: "general-purpose"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        apiVersion: kubelet.config.k8s.io/v1beta1
        evictionHard:
          memory.available: "200Mi"
    labels:
      instance-group: "memory-intensive"
    extraMounts:
      - hostPath: /var/lib/docker
        containerPath: /var/lib/docker