name: Kube Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'Select the Base Image (e.g., ubuntu:20.04, node:14, python:3.9)'
        required: true
        default: 'ubuntu:20.04'
      packages:
        description: 'Comma-separated list of packages to install (e.g., curl, vim, git)'
        required: true
        default: 'curl,vim,git'
      memory_request:
        description: 'Memory Request (e.g., 8Gi)'
        required: true
        default: '8Gi'
      cpu_request:
        description: 'CPU Request (e.g., 2)'
        required: true
        default: '2'

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set working directory to kube and list files
        working-directory: ./kube
        run: |
          pwd
          ls -l

      - name: Install kind and kubectl
        run: |
          sudo curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          sudo chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          sudo curl -Lo kubectl https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
          sudo chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Generate Dockerfile
        working-directory: /home/runner/work/swish-project/swish-project/kube
        run: |
          echo "FROM ${{ github.event.inputs.base_image }}" > Dockerfile
          packages="${{ github.event.inputs.packages }}"
          packages="${packages//,/ }"  # Replace commas with spaces
          echo "ENV DEBIAN_FRONTEND=noninteractive" >> Dockerfile 
          echo "RUN apt-get update && apt-get install -y $packages && apt-get clean && rm -rf /var/lib/apt/lists/*" >> Dockerfile
          echo "" >> Dockerfile
          echo "# Install necessary packages" >> Dockerfile
          echo "RUN apt-get update && apt-get install -y openssh-server" >> Dockerfile
          echo "RUN mkdir /var/run/sshd && \\" >> Dockerfile
          echo "    echo 'root:root' | chpasswd && \\" >> Dockerfile
          echo "    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \\" >> Dockerfile
          echo "    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config" >> Dockerfile
          echo "" >> Dockerfile
          echo "# Expose the default SSH port" >> Dockerfile
          echo "EXPOSE 22" >> Dockerfile
          echo "" >> Dockerfile
          echo "# Start the SSH server" >> Dockerfile
          echo 'CMD ["/usr/sbin/sshd", "-D"]' >> Dockerfile

      - name: Build Docker image
        working-directory: /home/runner/work/swish-project/swish-project/kube
        run: |
          docker build -t deploy-env:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUBPW }}

      - name: Tag and Push Docker Image to Docker Hub
        run: |
          docker tag deploy-env:latest boluwole/deploy-env:latest
          docker push boluwole/deploy-env:latest

      - name: Create kind cluster
        run: |
          kind create cluster --config /home/runner/work/swish-project/swish-project/kube/kind-cluster-config.yaml
          kind get kubeconfig > $HOME/.kube/config

      - name: Install Prometheus Operator with Helm
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace

      - name: Deploy to Kubernetes with Resource Requests
        run: |
          kubectl apply -f /home/runner/work/swish-project/swish-project/kube/service.yaml
          kubectl apply -f /home/runner/work/swish-project/swish-project/kube/alertmanager-config.yaml        
          kubectl apply -f /home/runner/work/swish-project/swish-project/kube/deployment.yaml
          kubectl set resources deployment deploy-env \
            --limits=memory=${{ github.event.inputs.memory_request }},cpu=${{ github.event.inputs.cpu_request }} \
            --requests=memory=${{ github.event.inputs.memory_request }},cpu=${{ github.event.inputs.cpu_request }}

      - name: Expose Services
        run: |
          kubectl expose deployment deploy-env --type=NodePort --name=dev-environment-service --port=8080
          kubectl expose deployment deploy-env --type=NodePort --name=dev-environment-ssh --port=2222

      - name: Install Metrics Server
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          kubectl patch deployment metrics-server -n kube-system --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--kubelet-insecure-tls"}]'
      - name: Describe Deploy Env Pod
        run: |
          kubectl describe pod -n default -l app=deploy-env
      - name: Wait for Metrics Server to be ready (Proceed on Failure)
        continue-on-error: true
        run: |
          echo "Waiting for Metrics Server to be ready..."
          kubectl wait --namespace kube-system \
            --for=condition=Ready pod \
            --selector=k8s-app=metrics-server \
            --timeout=120s || echo "Metrics Server did not become ready, continuing anyway."

      - name: View pods
        run: |
          kubectl get pods --all-namespaces
      - name: Monitor Resource Usage
        continue-on-error: true
        run: |
          echo "Getting exact pod name..."
          POD_NAME=$(kubectl get pods -n default -l app=deploy-env -o jsonpath="{.items[0].metadata.name}")
          echo "Pod name found: $POD_NAME"
          kubectl top pod $POD_NAME -n default > usage_data.txt || echo "Pod not ready for metrics"
      - name: Upload Usage Data
        uses: actions/upload-artifact@v4
        with:
          name: Usage Data
          path: usage_data.txt
