name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify kube directory exists
        run: |
          ls -l ./kube

      - name: Set working directory to kube and list files
        working-directory: ./kube
        run: |
          pwd
          ls -l

      - name: Install kind and kubectl
        run: |
          sudo curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          sudo chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          sudo curl -Lo kubectl https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl
          sudo chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Build Docker image
        run: |
          docker build -t dev-env:latest -f dockerfile .

      - name: Create kind cluster
        run: |
          kind create cluster --config kind-cluster-config.yaml
          kind get kubeconfig > $HOME/.kube/config

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f prom-stack.yaml
          kubectl apply -f alertmanager-config.yaml

      - name: Expose Services
        run: |
          kubectl expose deployment dev-environment --type=NodePort --name=dev-environment-service --port=8080
          kubectl expose deployment dev-environment --type=NodePort --name=dev-environment-ssh --port=22

      - name: Monitor Resource Usage
        run: |
          kubectl top pod dev-environment > usage_data.txt

      - name: Upload Usage Data
        uses: actions/upload-artifact@v3
        with:
          name: Usage Data
          path: usage_data.txt